name: Trae Decor
favicon: null
layout_spectrum: 0.46501
typography_spectrum: 0.79973
title: Beautifully Designed Decor @ very reasonable prices
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c94a3'
    - '#ffffff'
    - '#bdc7cc'
    - '#404842'
    - '#090a0b'
  brandStrength: 1
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
